// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by "stringer -type=Stability"; DO NOT EDIT.

package feature

import "strconv"

const _Stability_name = "UndefinedStableBetaExperimental"

var _Stability_index = [...]uint8{0, 9, 15, 19, 31}

func (i Stability) String() string {
	if i < 0 || i >= Stability(len(_Stability_index)-1) {
		return "Stability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stability_name[_Stability_index[i]:_Stability_index[i+1]]
}
